# Generated by Django 3.0.5 on 2020-05-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200430_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='update_at',
        ),
    ]
