# Generated by Django 3.0.5 on 2020-05-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200508_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='instagram',
            new_name='linkedin',
        ),
    ]
