# Generated by Django 3.0.5 on 2020-05-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cimages',
            name='image',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
    ]
