# Generated by Django 3.0.5 on 2020-04-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
