# Generated by Django 3.0.5 on 2020-05-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200508_1548'),
        ('photo', '0005_auto_20200429_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userprofil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.UserProfile'),
            preserve_default=False,
        ),
    ]
